apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: unvypbonh-nodejs 
  janus-idp.io/tekton: unvypbonh-nodejs
  backstage.io/kubernetes-id: unvypbonh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: unvypbonh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  